
SELECT
    -- clean + rename columns
    STORE_ID,
    CAST(FACT_DATE AS DATE) AS FACT_DATE,
    CAST(TEMPERATURE AS FLOAT) AS TEMPERATURE,
    CAST(FUEL_PRICE AS FLOAT) AS FUEL_PRICE,
    MARKDOWN1,
    MARKDOWN2,
    MARKDOWN3,
    MARKDOWN4,
    MARKDOWN5,
    CAST(CPI AS FLOAT) AS CPI,
    CASE WHEN UNEMPLOYMENT = 'NA' THEN 0.0 ELSE CAST(UNEMPLOYMENT AS FLOAT) END AS UNEMPLOYMENT.
    IS_HOLIDAY,
    INSERT_DTS,
    UPDATE_DTS,
    -- metadata columns from Snowpipe
    SOURCE_FILE_NAME,
    SOURCE_FILE_ROW_NUMBER
FROM {{ source('bronze', 'WALLMART_FACT') }}