
SELECT
    -- clean + rename columns
    STORE_ID,
    CAST(FACT_DATE AS DATE) AS FACT_DATE,
    CAST(TEMPERATURE AS FLOAT) AS TEMPERATURE,
    CAST(FUEL_PRICE AS FLOAT) AS FUEL_PRICE,
    COALESCE(TRY_CAST(MARKDOWN1 AS FLOAT), NULL) AS MARKDOWN1,
    COALESCE(TRY_CAST(MARKDOWN2 AS FLOAT), NULL) AS MARKDOWN2,
    COALESCE(TRY_CAST(MARKDOWN3 AS FLOAT), NULL) AS MARKDOWN3,
    COALESCE(TRY_CAST(MARKDOWN4 AS FLOAT), NULL) AS MARKDOWN4,
    COALESCE(TRY_CAST(MARKDOWN5 AS FLOAT), NULL) AS MARKDOWN5,
    COALESCE(TRY_CAST(CPI AS FLOAT), NULL) AS CPI,
    COALESCE(TRY_CAST(UNEMPLOYMENT AS FLOAT), NULL) AS UNEMPLOYMENT,
    IS_HOLIDAY,
    INSERT_DTS,
    UPDATE_DTS,
    -- metadata columns from Snowpipe
    SOURCE_FILE_NAME,
    SOURCE_FILE_ROW_NUMBER
FROM {{ source('bronze', 'WALLMART_FACT') }}